### ISSUE TITLE
Helper/Title on images in toolbar is missing.

### ISSUE THREAD

**Issue by joebordes** [Luke1982/mltheme-corebos#1]
When you hover the mouse over the image buttons in the toolbar, there is no helper text in the title like there is in softed. I think this text is useful and shouldn't be lost.

![buttonhovertitle](https://cloud.githubusercontent.com/assets/1237191/17462904/ab1035be-5cbb-11e6-86d0-50244afeafd5.png)

**Comment by Luke1982** [comment]
I'll look into this, thanks!

**Comment by Luke1982** [comment]
This issue is quite serious in the following way: I've setup these icons as vector icons. Basically setting a "display: none" on the image itself but creating a "before" psuedo-element on it that is displayed as a block and holds the vector image (which is basically a text-character). The text on the hover was the title attribute of the image. Since the image itself is no longer there, the 'helptext' that belongs to the image is also gone. The only way to retrieve it is by creating an actual image and not use the vector "before" elements.

**Comment by joebordes** [comment]
I dedicated some time to this and I have to agree with you. If we want to use icon-fonts there and the helper text we will have to modify the template.
Can't you just export the icon as a .gif and put it in your theme?
If not, what do you propose? How can I help?

**Comment by Luke1982** [comment]
Yes, it seems this is the only way to keep the tooltip feature. Exporting the SVG's to GIF is no problem. The ony thing I would like to propose for future development is a JS image loader. I've use one before, I think it was called 'imagesloaded' by the creator of masonry. The reason I am proposing this is it can reduce perceived screen loading times on slower servers, which is why I used the SVG's in the first place.

**Comment by joebordes** [comment]
give more information and we can discuss the best way forward

**Comment by Luke1982** [comment]
I'll spend some time on the theme shortly, first item of business will be researching this.

**Comment by Luke1982** [comment]
I can also write a small plugin in the general.js file that does this.. Let me work on this.

**Comment by Luke1982** [comment]
Please check the theme now. I've completely reworked the buttonlist to accomodate images (so that the helper text is visible) and changed the styling so that it will stand out more, and has more cohesion. Also, the folder structure is changed. This is because some images are not in the individual theme's folder, but in the general 'themes/images' folder. So you CAN copy just the MajorLabel theme folder, but you'll be missing some images.

**Comment by joebordes** [comment]
Looks good :-)
